DROP SCHEMA IF EXISTS JITY;
CREATE SCHEMA IF NOT EXISTS JITY;

-- -----------------------------------------------------
-- Table JOB
-- -----------------------------------------------------
DROP TABLE IF EXISTS JITY.JOB;

CREATE TABLE IF NOT EXISTS JITY.JOB (
  ID DOUBLE NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR(25) NOT NULL ,
  DESCRIPTION VARCHAR(45) NULL ,
  HOSTNAME VARCHAR(45) NOT NULL ,
  USER VARCHAR(45) NOT NULL ,
  COMMAND_PATH VARCHAR(255) NOT NULL ,
  IS_ACTIVED TINYINT(1) NOT NULL DEFAULT TRUE ,
  PRIMARY KEY (ID)
 );
  

-- -----------------------------------------------------
-- Table EXEC_STATUS
-- -----------------------------------------------------
DROP TABLE IF EXISTS JITY.EXEC_STATUS;

CREATE TABLE IF NOT EXISTS JITY.EXEC_STATUS (
  ID DOUBLE NOT NULL AUTO_INCREMENT ,
  DATE_BEGIN DATETIME NOT NULL,
  DATE_END DATETIME NULL ,
  STATUS INT NOT NULL,
  JOB_ID DOUBLE NOT NULL ,
  PRIMARY KEY (ID) ,
  CONSTRAINT FK_EXEC_STATUS_JOB
    FOREIGN KEY (JOB_ID)
    REFERENCES JITY.JOB(ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table CALENDAR
-- -----------------------------------------------------
DROP TABLE IF EXISTS JITY.CALENDAR ;

CREATE  TABLE IF NOT EXISTS JITY.CALENDAR (
  ID DOUBLE NOT NULL ,
  NAME VARCHAR(25) NOT NULL ,
  DESCRIPTION VARCHAR(45) NULL ,
  YEAR YEAR NOT NULL ,
  OPEN_DAYS VARCHAR(366) NOT NULL COMMENT 'String indiquate if the day of year  is open (0 for closed, 1 for opened)' ,
  PRIMARY KEY (ID) );


-- -----------------------------------------------------
-- Table DATE_CONSTRAINT
-- -----------------------------------------------------
DROP TABLE IF EXISTS JITY.DATE_CONSTRAINT ;

CREATE  TABLE IF NOT EXISTS JITY.DATE_CONSTRAINT (
  ID DOUBLE NOT NULL ,
  PLANIF_RULE VARCHAR(255) NOT NULL ,
  CALENDAR_ID DOUBLE NOT NULL ,
  PRIMARY KEY (ID) ,
  CONSTRAINT FK_DATE_CONSTRAINT_CALENDAR
    FOREIGN KEY (CALENDAR_ID)
    REFERENCES JITY.CALENDAR(ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table EXEC_CONSTRAINT
-- -----------------------------------------------------
DROP TABLE IF EXISTS JITY.EXEC_CONSTRAINT ;

CREATE  TABLE IF NOT EXISTS JITY.EXEC_CONSTRAINT (
  JOB_ID DOUBLE NOT NULL ,
  DATE_CONSTRAINT_ID DOUBLE NOT NULL ,
  CONSTRAINT FK_EXEC_CONSTRAINT_JOB
    FOREIGN KEY (JOB_ID)
    REFERENCES JITY.JOB(ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_EXEC_CONSTRAINT_DATE_CONSTRAINT
    FOREIGN KEY (DATE_CONSTRAINT_ID)
    REFERENCES JITY.DATE_CONSTRAINT(ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
